#!/usr/bin/env bash

set -e

## Check if -u or --pull is passed
if [[ "$1" == "-u" || "$1" == "--pull" ]]; then
  git pull
fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

eval "$(thefuck --alias)"
# if fuck is not installed, install it
if ! command -v fuck &> /dev/null; then
  # install thefuck here
  pip3 install thefuck --user 
fi

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
